mlflow:
  enabled: ${IS_MLFLOW_ENABLED}
  image: ${MLFLOW_IMAGE}
  backendStoreUri: postgresql://${MLFLOW_DB_USER}:${MLFLOW_DB_PWD}@mlflow-postgres-service:5432/${MLFLOW_DB}
  artifactRoot: s3://mlflow/

postgresql:
  enabled: ${IS_MLFLOW_ENABLED}
  auth:
    user: ${MLFLOW_DB_USER}
    password: ${MLFLOW_DB_PWD}
    database: ${MLFLOW_DB}
  storage: 10Gi

minio:
  enabled: ${IS_MLFLOW_ENABLED}
  user: ${MINIO_USER}
  password: ${MINIO_PWD}
  storage: 10Gi

api:
  enabled: false
  image: your-docker-registry/sentiment-api:latest

streamlit:
  enabled: false
  image: your-docker-registry/streamlit-ui:latest

azure:
  instrumentationKey: <YOUR_AZURE_INSIGHT_KEY>

ingress:
  enabled: true
  className: nginx
  mlflow:
    host: ${MLFLOW_HOST}
  minio:
    host: ${MINIO_HOST}
  api:
    host: ${API_HOST}
  streamlit:
    host: ${STREAMLIT_HOST}