name: Sentiments CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
  push:
    branches: [main]
    paths:
      - 'api/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SHA: ${{ github.sha }}

jobs:
  build:
    name: "🐳 Build & Push API Image"
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build api image
      uses: docker/build-push-action@v6
      with:
        context: ./api
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/sentiment-api:${{ env.SHA }}


