name: Sentiment CI - Main

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SHA: ${{ github.sha }}

jobs:
  build-mlflow-image:
    name: Build & Push MLflow Image
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build mlflow image
      uses: docker/build-push-action@v4
      with:
        context: ./mlflow
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/mlflow:${{ env.SHA }}
  build-api-image:
    name: Build & Push API Image
    runs-on: ubuntu-latest
    environment: docker-hub
    needs: build-mlflow-image
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build api image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/sentiment-api:${{ env.SHA }}
