name: Deploy Sentiment Services - CI

on:
  workflow_call:
    inputs:
      service:
        default: "Le service à deployer"
        required: true
        type: string
      sha:
        description: "Le SHA du commit"
        required: true
        type: string
      env_block:
        description: "les variables du values du chart helm encodé en base64"
        required: true
        type: string

jobs:
  deploy:
    name: "🚀 Deploying ${{ inputs.service }} with Helm !"
    runs-on: ubuntu-latest
    environment: hetzner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Decode and export variables
        run: |
          echo "${{ inputs.env_block }}" | base64 -d > .envvars
          cat .envvars
          set -a
          source .envvars
          set +a 

      - name: Override helm chart values
        run: |
          envsubst < deployments/values.yml > override_values.yml
          cat override_values.yml

      - name: Deploy ${{ inputs.service }} via Helm
        run: |
          helm upgrade --install sentiment-stack ./sentiment-stack -f override_values.yml