name: Deploy Sentiment Services - CI

on:
  workflow_call:
    inputs:
      service:
        default: "Le service à deployer"
        required: true
        type: string
      sha:
        description: "Le SHA du commit"
        required: true
        type: string
      env_block:
        description: "les variables du values du chart helm encodé en base64"
        required: true
        type: string

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKER_EMAIL: ${{ secrets.DOCKERHUB_EMAIL }}

jobs:
  deploy:
    name: "🚀 Deploying ${{ inputs.service }}"
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Apply pod deployment
        run: |
          kubectl create secret docker-registry dockerhub-secret \
            --docker-username=${{ DOCKERHUB_USERNAME }} \
            --docker-password=${{ DOCKERHUB_PASSWORD }} \
            --docker-email=${{ DOCKERHUB_EMAIL }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Decode and export variables
        run: |
          echo "${{ inputs.env_block }}" | base64 -d > .envvars
          cat .envvars
          set -a
          source .envvars
          set +a 

      - name: Override helm chart values
        run: |
          envsubst < deployments/values.yml > override_values.yml

      - name: Deploy ${{ inputs.service }} via Helm
        run: |
          helm upgrade --install sentiment-stack ./sentiment-stack -f override_values.yml